### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by evamillan**
This PR adds integration tests for the login process and for adding, merging and deleting individuals using Puppeteer. The tests are run with `yarn test:integration [--url=BASE_URL]`.

A few caveats:
- The tests assume there is a user with a username `testusername` and password `password`.
- The base URL should be a test one since it will perform real operations on it.

### CODE REVIEW

**Review by sduenas — COMMENTED** [review]
I've been trying with several methods (`manage.py` or `sortinghatd --dev`) and with all, I get the same set of errors:
```
yarn test:integration --url=http://localhost:8080/
yarn run v1.22.10
$ jest --c=tests/integration/jest.config.js --runInBand --url=http://localhost:8080/
 FAIL  tests/integration/tests.spec.js (5.044s)
  ● Login › Does not log in with wrong credentials

    No node found for selector: #username

       7 |     await page.goto(`${BASE_URL}/login`, { waitUntil: "networkidle0" });
       8 | 
    >  9 |     await page.type("#username", "testusername");
         |     ^
      10 |     await page.type("#password", "wrongpassword");
      11 |     await expect(page).toClick('button', { text: "Log in" });
      12 | 

      at Object.assert (../../node_modules/puppeteer/src/common/assert.ts:23:21)
      at DOMWorld.type (../../node_modules/puppeteer/src/common/DOMWorld.ts:478:5)
      at Object.<anonymous> (tests.spec.js:9:5)

  ● Login › Logs in a user

    No node found for selector: #username

      18 |     await page.goto(`${BASE_URL}/login`, { waitUntil: "networkidle0" });
      19 | 
    > 20 |     await page.type("#username", "testusername");
         |     ^
      21 |     await page.type("#password", "password");
      22 |     await expect(page).toClick('button', { text: "Log in" });
      23 |     await page.waitForNavigation();

      at Object.assert (../../node_modules/puppeteer/src/common/assert.ts:23:21)
      at DOMWorld.type (../../node_modules/puppeteer/src/common/DOMWorld.ts:478:5)
      at Object.<anonymous> (tests.spec.js:20:5)

  ● Operations › Adds individuals

    No node found for selector: .js-add-individual

      31 |     await page.goto(BASE_URL, { waitUntil: "networkidle0" });
      32 | 
    > 33 |     await page.click(".js-add-individual");
         |     ^
      34 |     await page.click("label", { text: "Name" });
      35 |     await page.keyboard.type("John Smith");
      36 |     await page.click("label", { text: "Source" });

      at Object.assert (../../node_modules/puppeteer/src/common/assert.ts:23:21)
      at DOMWorld.click (../../node_modules/puppeteer/src/common/DOMWorld.ts:439:5)
      at Object.<anonymous> (tests.spec.js:33:5)

  ● Operations › Merges individuals

    TypeError: Cannot read property 'evaluate' of null

      54 |     // Get the number of individuals before the merge
      55 |     const counter = await page.$(".individuals .v-chip__content");
    > 56 |     const beforeCount = await counter.evaluate(el => parseInt(el.textContent));
         |                                       ^
      57 | 
      58 |     await page.setDragInterception(true);
      59 |     const individuals = await page.$$("tr[draggable]");

      at Object.<anonymous> (tests.spec.js:56:39)

  ● Operations › Deletes individuals

    TypeError: Cannot read property 'evaluate' of null

      79 | 
      80 |     let counter = await page.$(".individuals .v-chip__content");
    > 81 |     const beforeCount = await counter.evaluate(el => parseInt(el.textContent));
         |                                       ^
      82 | 
      83 |     const individual = await page.$("tr[draggable] .text-right");
      84 |     await individual.click();

      at Object.<anonymous> (tests.spec.js:81:39)

Test Suites: 1 failed, 1 total
Tests:       5 failed, 5 total
Snapshots:   0 total
Time:        5.064s, estimated 6s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any idea about what's happening?

**Comment by evamillan** [comment]
It may be the URL. In your error log it looks like you are using `http://localhost:8080/`, so the tests will try to open `http://localhost:8080//login`, which doesn't exist. Can you try with `yarn test:integration --url=http://localhost:8080` (without the last `/`)?

**Comment by sduenas** [comment]
It was that but I get some other errors. 

```
$ yarn test:integration --url=http://localhost:8080
yarn run v1.22.10
$ jest --c=tests/integration/jest.config.js --runInBand --url=http://localhost:8080
 FAIL  tests/integration/tests.spec.js (6.297s)
  ● Operations › Adds individuals

    TimeoutError: Text not found "John Smith"

      waiting for function failed: timeout 500ms exceeded

  ● Operations › Merges individuals

    TypeError: Cannot read property 'dragAndDrop' of undefined

      58 |     await page.setDragInterception(true);
      59 |     const individuals = await page.$$("tr[draggable]");
    > 60 |     await individuals[1].dragAndDrop(individuals[0]);
         |                          ^
      61 | 
      62 |     await expect(page).toMatch("Merge the selected items?");
      63 |     await expect(page).toClick("button", { text: "Confirm" });

      at Object.<anonymous> (tests.spec.js:60:26)

  ● Operations › Deletes individuals

    TypeError: Cannot read property 'click' of null

      82 | 
      83 |     const individual = await page.$("tr[draggable] .text-right");
    > 84 |     await individual.click();
         |                      ^
      85 | 
      86 |     await page.waitFor(500);
      87 | 

      at Object.<anonymous> (tests.spec.js:84:22)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 2 passed, 5 total
Snapshots:   0 total
Time:        6.311s, estimated 7s
Ran all test suites.
error Command failed with exit code 1
```

Maybe we should fix the problem with the `/` so it doesn't create confusion. Also, these tests can wipe out the database. I had some identities an all of them are gone.

**Comment by evamillan** [comment]
I've made a few changes to improve the tests:

- Added a function to remove the `/` from the url if it ends with one.
- Redid the merge and delete tests to first order the individuals by last updated date and check if they are the ones created on the previous test.
- Added a `jest-puppeteer.config.js` file to set whether the tests are running on headless mode. Setting it to `false` launches a live browser that will make it easier to debug.

**Comment by evamillan** [comment]
I made some more changes: 
- longer timeouts to avoid the `waiting for function failed: timeout 500ms exceeded` error
- larger browser viewport to fit more elements on screen
- click some problematic buttons with javascript instead of with puppeteer's mouse
- merge individuals using the "merge" button instead of using drag and drop

I ran the tests 35 times after these changes and they all passed.

**Review by sduenas — APPROVED** [review]
LGTM

Thanks for taking care of this. Would you mind to rebase it before merging it?

**Comment by evamillan** [comment]
Done!

**Pull request merged**
