### PR TITLE
[gha] Add workflow to check if a changelog was included

### PR DESCRIPTION
**Pull request by vchrombie**
This PR adds a github action workflow to check if a changelog file was included in the pull request whenever there is a change to the source code and validate the contents if it is empty or valid YAML file.

Related to https://github.com/chaoss/grimoirelab/issues/466

### CODE REVIEW

**Comment by sduenas** [comment]
Can you rebase this @vchrombie ? I see there's another PR, should we close that one?

**Comment by vchrombie** [comment]
> Can you rebase this @vchrombie ? 

Yups, I have rebased it. How does it look now?

> I see there's another PR, should we close that one?

Well, yes but that's is for the muggle branch. This PR is for the master branch. I think we need this workflow in the muggle branch too. WDYT?

Also, there is slight difference

`master` branch
```
on:
  pull_request:
    paths:
      - 'sortinghat/**'
```

`muggle` branch (since we have source code in the `ui/` folder too
```
on:
  pull_request:
    paths:
      - 'sortinghat/**'
      - 'ui/**'
```

Please let me know what do you think.

**Review by sduenas — APPROVED** [review]
LGTM

**Comment by sduenas** [comment]
> > Can you rebase this @vchrombie ?
> 
> Yups, I have rebased it. How does it look now? @sduenas
> 
> > I see there's another PR, should we close that one?
> 
> Well, yes but that's is for the muggle branch. This PR is for the master branch. I think we need this workflow in the muggle branch too. WDYT?
> 
> Also, there is slight difference
> 
> `master` branch
> 
> ```
> on:
>   pull_request:
>     paths:
>       - 'sortinghat/**'
> ```
> 
> `muggle` branch (since we have source code in the `ui/` folder too
> 
> ```
> on:
>   pull_request:
>     paths:
>       - 'sortinghat/**'
>       - 'ui/**'
> ```
> 
> Please let me know what do you think.

Understood! Sorry I didn't see they are PRs on different branches.

**Pull request closed without merging**
