### PR TITLE
Add requirements file

### PR DESCRIPTION
**Pull request by snack0verflow**
This commit adds the requirements files for this repository.

### CODE REVIEW

**Comment by snack0verflow** [comment]
@sduenas Some tests have f-string literals like:

> File "/home/travis/build/chaoss/grimoirelab-sortinghat/.eggs/Jinja2-3.0.0a1-py3.5.egg/jinja2/bccache.py", line 207
    dirname = f"_jinja2-cache-{os.getuid()}"
                                           ^
SyntaxError: invalid syntax
----------------------------------------------------------------------

> Ran 413 tests in 13.267s
> FAILED (errors=21)
> The command "coverage run --source=sortinghat setup.py test" exited with 1.

This is a feature introduced in Python 3.6 https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498

**Comment by sduenas** [comment]
> @sduenas Doesn't seem related to my change. Some tests have f-string literals like:
> 
> > File "/home/travis/build/chaoss/grimoirelab-sortinghat/.eggs/Jinja2-3.0.0a1-py3.5.egg/jinja2/bccache.py", line 207
> > dirname = f"_jinja2-cache-{os.getuid()}"
> > ^
> > SyntaxError: invalid syntax
> 
> > Ran 413 tests in 13.267s
> > FAILED (errors=21)
> > The command "coverage run --source=sortinghat setup.py test" exited with 1.
> 
> This is a feature introduced in Python 3.6 https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498

Then we should start using a version of Jinja that don't have f-strings. The version is not pinned, so it will install the latest possible. I suggest you to find a version that work with Python 3.5.

**Comment by snack0verflow** [comment]
@sduenas According to https://pypi.org/project/Jinja2/ the latest version of jinja2 (2.11.1) should work with python 3.5

**Comment by sduenas** [comment]
> @sduenas According to https://pypi.org/project/Jinja2/ the latest version of jinja2 (2.11.1) should work with python 3.5
> The build checks are not running this version.

Ok. Let's pin this version in requirements and setup files and let's check if it works.

**Comment by snack0verflow** [comment]
@sduenas specifying the correct version of jinja2 in setup.py will work? Do I need to take care of anything else for running the Travis CI build with the correct version?

**Comment by sduenas** [comment]
> @sduenas specifying the correct version of jinja2 in setup.py will work? Do I need to take care of anything else for running the Travis CI build with the correct version?

Nop. It will work that way. Be sure you update both `requirements.txt` and `setup.py`.

**Comment by snack0verflow** [comment]
@sduenas The builds have passed

**Comment by sduenas** [comment]
Thanks! PR merged.

**Pull request merged**
