### PR TITLE
[ui] Improve UUID visualization on IndividualEntry

### PR DESCRIPTION
**Pull request by evamillan**
Limits the size of the uuid chip on `IndividualEntry` to 7 characters. The full uuid is displayed on hover.

### CODE REVIEW

**Review by sduenas — CHANGES_REQUESTED** [review]
I don't like much how the UUID expands. It's a bit odd. Would it be possible to show the UUID on hover like in this example?

info

**Comment by evamillan** [comment]
I've changed it to a tooltip.

**Review by sduenas — APPROVED** [review]
Thanks. It looks much better this way.

LGTM.

**Comment by sduenas** [comment]
BTW, would you mind to rebase this PR to 'muggle' branch?

**Comment by evamillan** [comment]
Done!

**Pull request merged**
