### PR TITLE
[ui] Show profile information when clicking on an individual card

### PR DESCRIPTION
**Pull request by evamillan**
Adds the `ProfileList` component, which displays a list
of `ProfileCards` when their corresponding `IndividualCard` is selected
on `IndividualsGrid'. The selected cards are stored in the Vuex state
so that they can be retrieved anywhere throughout the app.

### CODE REVIEW

**Review by sduenas — CHANGES_REQUESTED** [review]
I've been testing it and I two problems: 

* When clicking over the lock button the card is selected.
* If you click on individuals that are on the bottom of the page the selected panel stays on the top of the page. Probably it should scroll down with the page.

**Comment by sduenas** [comment]
> I've been testing it and I two problems:
> 
>     * When clicking over the lock button the card is selected.
> 
I was wrong and this behaviour doesn't happen.

**Comment by evamillan** [comment]
@sduenas I updated the PR with the changes you requested.

**Review by sduenas — CHANGES_REQUESTED** [review]
The new patch fixes the problems commented before but I found these warnings while running `yarn serve`:

```
 WARNING  Compiled with 1 warnings                                                                                                                                                                       7:07:22 PM

Module Warning (from ./node_modules/eslint-loader/index.js):

/home/sduenas/devel/grimoirelab/sortinghat/ui/src/components/ProfileCard.vue
   11:27  warning  Replace `>Identities·({{·identitiesCount·}})</v-list-item-title` with `⏎··········>Identities·({{·identitiesCount·}})</v-list-item-title⏎········`                     prettier/prettier
   22:20  warning  Replace `⏎··············v-text="selectSourceIcon(source.name)"⏎··············left⏎···········` with `·v-text="selectSourceIcon(source.name)"·left`                     prettier/prettier
   32:21  warning  Replace `⏎··········v-for="identity·in·source.identities"⏎··········:key="identity.uuid"⏎········` with `·v-for="identity·in·source.identities"·:key="identity.uuid"`  prettier/prettier
   60:29  warning  Replace `>Organizations·({{·enrollments.length·}})</v-list-item-title` with `⏎············>Organizations·({{·enrollments.length·}})</v-list-item-title⏎··········`     prettier/prettier
  130:29  warning  Replace `'T')[0]` with `"T")[0];`                                                                                                                                      prettier/prettier
  135:40  warning  Replace `b)·=>·a·+·b.identities.length,·0)` with `·b)·=>·a·+·b.identities.length,·0);`                                                                                 prettier/prettier
  138:60  warning  Insert `;`                                                                                                                                                             prettier/prettier

✖ 7 problems (0 errors, 7 warnings)
  0 errors and 7 warnings potentially fixable with the `--fix` option.
```

**Comment by evamillan** [comment]
Thanks, I fixed the warnings.

**Review by sduenas — APPROVED** [review]
LGTM

**Pull request merged**
