### PR TITLE
Filter individuals by enrollment 

### PR DESCRIPTION
**Pull request by evamillan**
Adds the `enrollment` filter to the `individuals` query, which returns a list of individuals enrolled in the given organization.
The search syntax in the UI is `enrollment:"organization name"`.

### CODE REVIEW

**Review by sduenas — CHANGES_REQUESTED** [review]
In overall, it looks good. Although, in the tests, would you mind to add two more enrollments for that individual, one with any given name an another with `Bit Company`, so you can check two more things:

-  The filter "bit" returns two enrollments.
- The filter `Bit Company` returns only one and that the case "Organizations that include spaces should be wrapped between double quotes" works.

**Comment by evamillan** [comment]
I updated the PR adding those test cases.

**Review by sduenas — APPROVED** [review]
LGTM. Would you mind to rebase it?

**Comment by evamillan** [comment]
Done.

**Review by sduenas — APPROVED** [review]
LGTM

**Pull request merged**
