### PR TITLE
[ui] Merge individuals on the workspace using drag and drop 

### PR DESCRIPTION
**Pull request by evamillan**
Individuals can be merged by dragging them from the table and dropping them into an individual card in the workspace. The workspace is then updated with the new individual.

### CODE REVIEW

**Review by sduenas — APPROVED** [review]
LGTM. I have a minor question, though.

Is it possible to have a different animation when dragging several individuals at once? It looks like I was only moving and merging one, not all the selected individuals.

**Comment by evamillan** [comment]
You can only drag one individual at a time, just like in the table. Should you be able to move all the selected ones at once?

**Comment by sduenas** [comment]
> You can only drag one individual at a time, just like in the table. Should you be able to move all the selected ones at once?

I think it should. Otherwise, users would feel odd that only the one dragged is merged when there are others selected for that operation.

**Comment by evamillan** [comment]
That makes sense, but it would change the current logic of the drag and drop quite a bit. Should I change it here or make a different issue and PR for it?

**Comment by sduenas** [comment]
> That makes sense, but it would change the current logic of the drag and drop quite a bit. Should I change it here or make a different issue and PR for it?

I think you can change it here. It's part of the requirements for this task.

**Comment by evamillan** [comment]
I updated the PR.

**Pull request merged**
