### PR TITLE
[core] Enroll individuals in teams

### PR DESCRIPTION
**Pull request by evamillan**
This PR allows individuals to be enrolled in teams.
- The `organization` field in the `Enrollment` model is renamed to `group`.
- A `find_group` function is added in order to search for a group by its name and parent organization.
- An optional `parent_org` parameter to identify the team is added to the `api.py` and `schema.py` functions that enroll, withdraw and update enrollments.

### CODE REVIEW

**Review by jjmerchante — CHANGES_REQUESTED** [review]
Some minor comments

**Comment by evamillan** [comment]
@jjmerchante Thanks for the comments, I've updated the PR with the changes. I've also changed the `withdraw` function at api.py, which was also passing `group` instead of `group.name` to `search_enrollments_in_period`.

**Comment by jjmerchante** [comment]
LGTM

**Review by sduenas — APPROVED** [review]
LGTM

**Comment by sduenas** [comment]
@evamillan would you mind to rebase your changes?

**Comment by evamillan** [comment]
@sduenas Done.

**Pull request merged**
