### PR TITLE
[ui] Fix eslint errors

### PR DESCRIPTION
**Pull request by vchrombie**
This PR fixes the eslint errors of the web app code in the muggle branch. This is necessary as we have to add an eslint check in the github actions ci workflow.

### CODE REVIEW

**Comment by vchrombie** [comment]
@sduenas @evamillan, please review when you are free.
Thanks.

**Review by sduenas — COMMENTED** [review]
How have you tried this? We usually run `yarn lint` (inside `ui`) directory. I'm not sure if these are the same errors or different ones.

**Comment by vchrombie** [comment]
> How have you tried this? We usually run `yarn lint` (inside `ui`) directory. I'm not sure if these are the same errors or different ones.

Yeah, I use the same command too. 
```yml
      - name: Run ESLint
        working-directory: ./ui
        run: yarn lint
```
You can also check the [latest workflow](https://github.com/chaoss/grimoirelab-sortinghat/runs/2113612292?check_suite_focus=true) of the #481 PR frontend test suite.

**Comment by vchrombie** [comment]
I saw four types of errors when I execute `yarn lint`.

> error: 'storiesOf' is defined but never used (no-unused-vars) at src/components/...:

this line has to be removed from the file, doesn't affect the test suite in any way

> error: 'page'/'mount' is defined but never used (no-unused-vars) at .../.../...:

the arguments have to be removed, no effect on the test suite

> error: 'updateProfileResponse'/'deleteDomainResponse'/'filteredOrganizations' is assigned a value but never used (no-unused-vars) at tests/unit/...:

the variables are removed, no effect on test suite

> error: 'response' is assigned a value but never used (no-unused-vars) at tests/unit/...:

the tests fail if we remove this line so I added a small configuration to `ui/.eslintrc.js` rules to mark them as warnings

> error: 'spyOn' is not defined (no-undef) at tests/unit/...:

I had to add `jasmine: true` to `ui/.eslintrc.js` env, to avoid these errors

**Review by sduenas — APPROVED** [review]
Thanks for the clarification. Looks good to me.

**Pull request merged**
