### PR TITLE
Add organizations from the UI 

### PR DESCRIPTION
**Pull request by evamillan**
Implements the `OrganizationModal` component, which displays a form that allows an organization and its domains to be created. The component is embedded inside `OrganizationsTable` and opens when the "add" button is clicked, as requested in  #383 . Two new GraphQL mutations -`addOrganization` and `addDomain`- are added to save the changes in the database.

### CODE REVIEW

**Review by sduenas — CHANGES_REQUESTED** [review]
When a new organization is added with a domain that already exists, the app doesn't return any error. I think it should return an error.

**Comment by evamillan** [comment]
I updated the PR. Now the errors are shown on an alert so that the user is aware of them and can fix them.

**Review by sduenas — CHANGES_REQUESTED** [review]
When I add a domain that already exists I don't see any error on the app. Also, after adding it, when I click again to add a new organization, I can't write the name of the new org and also, the domain I tried to open before is on the form. You can see that behaviour in the next video:

error-new-org

**Comment by evamillan** [comment]
I updated the PR. Since it was confusing, the "add" button is now a "+" and instead of adding the domain to a list, it adds a new input.

**Review by sduenas — APPROVED** [review]
LGTM

**Pull request merged**
