### PR TITLE
[gha] Add workflow to check if a changelog was included

### PR DESCRIPTION
**Pull request by vchrombie**
This PR adds a github action workflow to check if a changelog file was included in the pull request whenever there is a change to the source (backend and frontend) and validate the contents if it is an empty or valid YAML file.

### CODE REVIEW

**Comment by vchrombie** [comment]
Related to https://github.com/chaoss/grimoirelab/issues/466

**Review by sduenas — APPROVED** [review]
LGTM

can you rebase it and I merge it?

**Comment by vchrombie** [comment]
> can you rebase it and I merge it?

Done :+1:

**Review by sduenas — COMMENTED** [review]
LGTM

**Pull request merged**
